#!/bin/bash
user="$1"
if [ -z "$user" ];
then
    user=$USER
fi
uid=$(id -u $user)
if [ "$uid" == "" ];
then
    exit 1
fi
echo "User: $user ($uid)"

group="$2"
if [ -z "$group" ];
then
    group=$(id -gn $user)
fi
gid=$(id -g $group)
if [ "$gid" == "" ];
then
    exit 1
fi
echo "Group: $group ($gid)"

docker build \
    -t mercurial \
    --build-arg hostuid=$uid \
    --build-arg hostgid=$gid \
    image
