#!/bin/bash
### BEGIN INIT INFO
# Provides:             mercurial
# Required-Start:       docker
# Required-Stop:        docker
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Mercurial web service
### END INIT INFO

IMAGENAME=mercurial
EXECUTABLE=/usr/sbin/mercurial
PIDFILE=/var/run/mercurial.pid

start() {
    shouldStart=
    if [ ! -e "$PIDFILE" ];
    then
        shouldStart=true;
    else
        CID=$(cat "$PIDFILE")
        if [ "$CID" == "" ];
        then
            shouldStart=true
        fi
    fi
    if [ "$shouldStart" = true ];
    then
        attempt=0;
        available=
        while [ $attempt -lt 10 ];
        do
            IID="$(docker images $IMAGENAME -q)"
            if [ "$IID" == "" ];
            then
                attempt=$((attempt+1))
                sleep 1
            else
                available=true
                break
            fi
        done
        if [ "$available" = true ];
        then
            OUTPUT=$("$EXECUTABLE")
            echo $OUTPUT > "$PIDFILE"
            echo $OUTPUT
        fi
    fi
}

stop() {
    if [ -e "$PIDFILE" ];
    then
        CID=$(cat "$PIDFILE")
        if [ "$CID" != "" ];
        then
            docker stop $CID
        fi
        rm "$PIDFILE"
    fi
}

status() {
    if [ -e "$PIDFILE" ];
    then
        CID=$(cat "$PIDFILE")
        if [ "$CID" == "" ];
        then
            echo "$IMAGENAME is NOT running"
            exit 1
        else
            echo "$IMAGENAME is running, pid=$CID"
        fi
    else
        echo "$IMAGENAME is NOT running"
        exit 1
    fi
}

case $1 in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $0 (start|stop|status|restart)"
        ;;
esac
