#!/bin/bash
docker run \
    --rm \
    --name hgweb \
    -d \
    -v /var/log/mercurial:/mercurial/logs \
    -v /mercurial/repositories:/mercurial/repositories \
    -v /mercurial/users:/mercurial/users \
    -p 8008:8008 \
        hgweb
