#!/bin/bash
docker run \
    --rm \
    --name mercurial \
    -d \
    -v /etc/localtime:/etc/localtime \
    -v /mercurial/repositories:/mercurial/repositories \
    -v /var/log/mercurial:/mercurial/logs \
    -v /var/backups/mercurial:/mercurial/backups \
    -p 8009:8009 \
        mercurial
