#!/bin/bash
if [ "$1" == "" ];
then
    echo "Usage: $0 <file>"
else
    TEMPTILE="/mercurial/backups/tmp_$1.tar.gz"
    FILE="/mercurial/backups/$1.tar.gz"

    cd /mercurial
    tar -czf $TEMPTILE repositories users
    mv $TEMPTILE $FILE
fi
