#!/bin/bash
if [ "$1" != "" ];
then
    TEMPTILE="/mercurial/backups/tmp_$1.tar.gz"
    FILE="/mercurial/backups/$1.tar.gz"

    cd /mercurial
    tar -czf $TEMPTILE repositories users
    mv $TEMPTILE $FILE
fi
