#!/bin/bash
startWebCmd="/mercurial/scripts/webStartup"
stopWebCmd="/mercurial/scripts/webShutdown"
startDummyCmd="/mercurial/scripts/containerDummy"
waitDummyCmd="ps axf | grep containerDummy | grep -v grep | awk '{print \"wait \" \$1}' | sh"
stopDummyCmd="ps axf | grep containerDummy | grep -v grep | awk '{print \"kill -9 \" \$1}' | sh"
