#!/bin/bash
if [ "$WEB_STYLE" != "" ];
then
    sed -i 's|style.*|style           = '"$WEB_STYLE"'|' /mercurial/hgweb.config
fi
if [ "$WEB_COLLAPSE" != "" ];
then
    sed -i 's|collapse.*|collapse        = '"$WEB_COLLAPSE"'|' /mercurial/hgweb.config
fi

if [ ! -f /mercurial/repositories/users ];
then
    cp /mercurial/users /mercurial/repositories
    chmod 644 /mercurial/repositories/users
fi

trap /mercurial/scripts/containerShutdown HUP SIGHUP INT SIGINT QUIT SIGQUIT TERM SIGTERM

source /mercurial/scripts/containerConfig
$startWebCmd & $startDummyCmd
eval $waitDummyCmd
