#!/bin/bash
FILE="/mercurial/backups/mercurial.tar.gz"

if [ -e "$FILE" ];
then
    cd /mercurial
    tar -xzf $FILE --exclude='users'
    cd /mercurial/repositories
    tar -xzf $FILE users
fi
