#!/bin/bash
if [ "$1" != "" ];
then
    FILE="/mercurial/backups/$1.tar.gz"

    if [ -e "$FILE" ];
    then
        cd /mercurial
        tar -xzf $FILE repositories
        cd /mercurial/repositories
        tar -xzf $FILE users
    fi
fi
