#!/bin/bash
if [ "$1" != "" ];
then
    FILE="/mercurial/backups/$1.tar.gz"
    source /mercurial/scripts/containerConfig

    if [ -e "$FILE" ];
    then
        $stopWebCmd

        cd /mercurial
        tar -xzf $FILE repositories

        $startWebCmd
    fi
fi
