#!/bin/bash
if [ "$1" != "" ];
then
    TEMPFILE="/mercurial/backups/tmp_$1.tar.gz"
    FILE="/mercurial/backups/$1.tar.gz"
    source /mercurial/scripts/containerConfig

    $stopWebCmd

    cd /mercurial
    tar -czf $TEMPFILE repositories
    rm -rf $FILE
    mv $TEMPFILE $FILE

    $startWebCmd
fi
